name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-with-awscli:$(date +%s)
      
    - name: GithubPackages-Docker
      # You may pin to the exact commit or the version.
      # uses: stijnvdkolk/githubpackages-docker@c64052692090e8cee503258fb0474f2fdd291926
      uses: stijnvdkolk/githubpackages-docker@v1.0.4
      with:
        name: lion2486/docker-with-awscli/docker-with-awscli
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
       
